// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OODProjectServer.Entities;
using System;

namespace OODProjectServer.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    [Migration("20181207222130_ThirdMigration")]
    partial class ThirdMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OODProjectServer.Entities.CoffeeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CoffeeId");

                    b.Property<string>("ImageLink1");

                    b.Property<string>("ImageLink2");

                    b.Property<string>("Name");

                    b.Property<int>("UserId");

                    b.Property<int?>("UserItemId");

                    b.HasKey("Id");

                    b.HasIndex("UserItemId");

                    b.ToTable("CoffeeItems");
                });

            modelBuilder.Entity("OODProjectServer.Entities.UserItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateStarted");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Rank");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserItems");
                });

            modelBuilder.Entity("OODProjectServer.Entities.CoffeeItem", b =>
                {
                    b.HasOne("OODProjectServer.Entities.UserItem")
                        .WithMany("CoffeeItems")
                        .HasForeignKey("UserItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
